aliases:
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: default
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - ansible
    - asciidoc
    - aws-nuke
    - aws-vault
    - awscli2
    - bfg-repo-cleaner
    - boundary
    - btop
    - buildah
    - bundix
    - cargo
    - certbot
    - cheat
    - chromedriver
    - cmake
    - consul
    - consul-template
    - curl
    - cyberchef
    - dconf2nix
    - dig
    - distrobox
    - dos2unix
    - dotnet-sdk_7
    - eza
    - ffmpeg
    - fio
    - gawk
    - gcc
    - geckodriver
    - git
    - git-lfs
    - github-cli
    - glances
    - gnum4
    - gnumake
    - go
    - google-cloud-sdk
    - graphviz
    - harfbuzz
    - helix
    - htop
    - hub
    - iftop
    - ioping
    - jd-gui
    - jq
    - kubectl
    - kubernetes-helm
    - kubetail
    - libtool
    - maven
    - meraki-cli
    - minikube
    - neofetch
    - neovim
    - nmap
    - nodejs
    - nomad
    - nomad-autoscaler
    - opentofu
    - oracle-instantclient
    - p7zip
    - packer
    - pcre2
    - pngcrush
    - powershell
    - progress
    - pv
    - python311Full
    - python311Packages.beautifulsoup4
    - python311Packages.boto3
    - python311Packages.botocore
    - python311Packages.flask
    - python311Packages.meraki
    - python311Packages.pip
    - python311Packages.pipx
    - python311Packages.pytz
    - python311Packages.requests
    - python311Packages.selenium
    - python311Packages.virtualenv
    - rar
    - rclone
    - restic
    - ruby
    - scalr-cli
    - selenium-server-standalone
    - shellcheck
    - skopeo
    - speedtest-cli
    - ssm-session-manager-plugin
    - starship
    - tcpdump
    - temurin-bin
    - terracognita
    - terraform
    - terraform-docs
    - terraform-ls
    - terraformer
    - tfsec
    - tldr
    - topgrade
    - tree
    - unar
    - unzip
    - vagrant
    - vault
    - vim
    - waypoint
    - wget
    - whois
    - yarn
    - yq
    - zsh

paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      home: ""
      hostname: dylantaylor-pc
      os: linux
      user:
        email: dylan@dylanmtaylor.com
        name: Dylan Taylor
        ssh_private_key_file: ~/.ssh/dylanmtaylor
        ssh_public_key_file: ~/.ssh/dylanmtaylor.pub
        username: dylan
      username: dylan
track: nixos-unstable
unfree: true
users: []
